line-length = 79
target-version = "py310"
src = ["src"]

include = ["src/**.py"]
lint.select = ["ALL"]
lint.ignore = [
   "ARG",
   "ANN",
   "D",
   "EM101",
   "EM102",
   "PT001",
   "PT023",
   "SIM108",
   "SIM114",
   "TRY003",
   "TCH003",
   "PLW2901",
   "RET505",
   "PLR0913",
   "UP038",
   "TCH001",
   "SIM103",
   "PERF401",
   "PLR2004",
   "PYI034",
]
